### ISSUE TITLE
Unable to detect  private browser on http site in chrome 

### ISSUE THREAD

**Issue by mritgupta** [jLynx/PrivateWindowCheck#4]
Note:- My website hosted on the HTTP protocol there not able to detect incognito mode for chrome.

Demo url:- http://vuelayout.com/PrivateWindowCheck.html

**Comment by jLynx** [comment]
Hi, Yes I forgot to mention. You need to be using HTTPS otherwise some of the detection methouds wont work, and there is no way around that. 
Its free and simple to get SSL these days, so there is no excuse not to have it. Look into "CloudFlare" or "Let's Encrypt"
