### ISSUE TITLE
No longer working on Dev Chrome

### ISSUE THREAD

**Issue by tixastronauta** [jLynx/PrivateWindowCheck#5]
Chrome version: Version 81.0.4033.2 (Official Build) dev (64-bit)
Screenshot: https://imgur.com/a/ZAEeV4r

**Comment by jLynx** [comment]
Its currently working for me on Version 79.0.3945.130 (Official Build) (64-bit). Are you on a dev build? The reason being as it says mine is up to date. Also can you please let me know what system you are running this on.

**Comment by tixastronauta** [comment]
Hi jLynx,

Yes I am on a Dev build `Version 81.0.4033.2 (Official Build) dev (64-bit)`, and under Mac OS. Here's my UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4033.2 Safari/537.36`

**Comment by jLynx** [comment]
Since its a dev build I will wait till it becomes official as things can change. So its not worth putting in the time to find a bypass for things to potentually change on release

**Comment by tixastronauta** [comment]
Good news. Just updated to the most recent dev build and its working now :)

**Comment by jLynx** [comment]
Great news
